### ISSUE TITLE
Oops! I Grid it again

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#179]
[link to the post](https://css.christmas/2019/4)

# How to Grid

Grid is used like Flexbox by setting the container with display: grid. Then you got to define how many rows and columns you want your grid to have with grid-template-columns and grid-template-rows. For instance:

![image](https://user-images.githubusercontent.com/29270715/73048124-3601d280-3ea0-11ea-9e34-c8a4f63dc7b7.png)

In this example, I have used 1fr (which stands for fraction) - to split the total space in the grid into three columns. This can also be written in a simpler way, by using repeat(3, 1fr) - which basically means repeat this column or row three times with the size of 1 fraction each.

After defining your columns and rows, you can decide whether to position your items by using grid lines or grid tracks. The numbers in the image below defines the grid lines for columns and rows, while tracks is the any group of cells. 

![image](https://user-images.githubusercontent.com/29270715/73048148-43b75800-3ea0-11ea-8501-ab4b6a38a48e.png)

With grid-lines, you place each item by defining from which column/row line to which column/row line you want your item stretch. For instance, if I want my .header item to stretch from the first grid line to the last grid line I could use: grid-column-start: 1 and grid-column-end: 4. However, I can also use a shorthand like grid-column: 1/4 . So instead of two codelines, you could use just one! Check out the example below:

To use grid tracks, you first have to define your grid-template-areas by naming each cell. Then tell your grid item which cell(s) it should cover with just one line, grid-area: header. I prefer this method as it is less code and easier to remember the cell names rather than the grid lines 😊. 

```css
.container {
  display: grid;
  grid-template-columns:  100px repeat(2, 1fr);
  grid-template-rows: 50px repeat(4, auto-fill) minmax(50px, 1fr);
  grid-template-areas: 
    "header header header"
    "sidebar main main"
    "sidebar posts links"
    "footer footer footer";
  grid-gap: 10px;
}


.header {
  background: lightcoral;
  grid-area: header;
}

.sidebar {
  background: lightseagreen;
  grid-area: sidebar;
}

main {
  background: Plum;
  grid-area: main;
}

.posts {
  background: Goldenrod;
  grid-area: posts;
}

.relevant-links {
  background: lightgreen;
  grid-area: links;
}

footer {
  background: lightblue;
  grid-area: footer;
}
```
If the placement of your grid items is not defined then all direct children of the container will automatically be placed inside of each cell in the grid. Simple, right? ✨

# What is good about Grid?

Grid really shines when it comes to dividing your web page into different parts without letting your markup suffer! Imagine going from having a layout with loads of nested flexboxes:

![image](https://user-images.githubusercontent.com/29270715/73048214-78c3aa80-3ea0-11ea-92e3-4ddc9d145473.png)

![image](https://user-images.githubusercontent.com/29270715/73048219-7f522200-3ea0-11ea-8965-cb2edbf65e08.png)

Not only does a pure flexbox layout require nested divs, but it also require more CSS to get padding or margin between each flex item to add spacing between your items. With Grid you can simply use grid-gap. 💁 

Of course, Grid is not here to replace Flexbox, but rather allow you to write concise and more semantically correct code! So instead of drowning in infinite nested flex boxer, how about you start using a combination of both Grid and Flexbox? You will definitiely reap of the results! ☺️ ✨
