### ISSUE TITLE
Fixed Headers and Jump Links? The Solution is scroll-margin-top 

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#269]
[link to the post](https://css-tricks.com/fixed-headers-and-jump-links-the-solution-is-scroll-margin-top/)

The problem: you click a jump link like <a href="#header-3">Jump</a> which links to something like <h3 id="header-3">Header</h3>. That's totally fine, until you have a position: fixed; header at the top of the page obscuring the header you're trying to link to!

Fixed headers have a nasty habit of hiding the element you're trying to link to. 

![image](https://user-images.githubusercontent.com/29270715/75223751-3bb84400-57cf-11ea-80c8-35594dd4b9ea.png)

here is actually a really straightforward way of handling this in CSS now. 

```css

h3 {
  scroll-margin-top: 5rem; /* whatever is a nice number that gets you past the header */
}
```

[here is a link to the demo](https://codepen.io/chriscoyier/pen/GRJpopp)
