### ISSUE TITLE
Styling The Good Ol' Button Element

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#270]
[link to the post](https://ishadeed.com/article/styling-the-good-old-button/)

# The Default Styles
Ok, this might sound easy but it’s interesting. Here is the default styling from Google Chrome’s user agent style sheet.

```css
.c-button {
    -webkit-writing-mode: horizontal-tb !important;
    -webkit-appearance: button;
    border-color: rgb(216, 216, 216) rgb(209, 209, 209) rgb(186, 186, 186);
    border-style: solid;
    border-width: 1px;
    padding: 1px 7px 2px;
    text-rendering: auto;
    color: initial;
    display: inline-block;
    text-align: start;
    margin: 0em;
    font: 400 11px system-ui;
}

```

Here is how the default button looks without resetting any styles:
![image](https://user-images.githubusercontent.com/29270715/75652159-78c67f80-5c82-11ea-8fbd-02ee1a6be8ae.png)

First, we need to override the appearance property. It’s used to provide a platform-native styling that is based on the user operating system (OS).

```css
.c-button {
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
}

```

![image](https://user-images.githubusercontent.com/29270715/75652193-8d0a7c80-5c82-11ea-84ac-8e83eba2c416.png)

Next, a couple of resets is needed before we start with the actual styling for the button. For example, border, background, and roundness.

```css
.c-button {
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
  border: 0;
  border-radius: 0;
  background: #ccc;
}
```
![image](https://user-images.githubusercontent.com/29270715/75652238-a90e1e00-5c82-11ea-92fd-080ec7470003.png)

# Basic Button Design
![image](https://user-images.githubusercontent.com/29270715/75652266-be834800-5c82-11ea-9b0d-6ea35b87f14f.png)

```css
.c-button {
  appearance: none;
  border: 0;
  border-radius: 5px;
  background: #4676D7;
  color: #fff;
  padding: 8px 16px;
  font-size: 16px;
}

```

![image](https://user-images.githubusercontent.com/29270715/75652310-d955bc80-5c82-11ea-9710-b671b4fa3c8e.png)

## Hover and Focus Styles
To give the user an indication when the button is hovered, it’s important to add a style for that interaction. The same concept applies to the focus style for a keyboard user.

As per this article by Ire Aderinokun, The order of adding the hover and focus pseudo-classes matter.

When the hover style is added before the focus one, each style works correctly. However, the issue lies in when focus is placed before hover. When the element is clicked with the mouse, the focus style won’t appear at all, and only the hover style will be visible.

![image](https://user-images.githubusercontent.com/29270715/75652380-04401080-5c83-11ea-922c-08d652cbea38.png)

```css
.c-button:hover {
  background: #1d49aa;
}

.c-button:focus {
  outline: none;
  box-shadow: 0 0 0 4px #cbd6ee;
}

```

## Minimum width for the button

Take the figure below, where there are some buttons with varying content length, in both English and Arabic. Without a minimum width, the button width can get too small if the text is short. It’s better to avoid that by using min-width.

![image](https://user-images.githubusercontent.com/29270715/75652458-35204580-5c83-11ea-89ae-4127d6f0d207.png)

```css
.c-button {
    min-width: 100px;
    /* other styles */
}
```

## Don’t Forget Padding
It might be tempting to not add horizontal padding for the button since it has a width and there is enough spacing on both sides, correct? No, this might be incorrect in case the content changed.

![image](https://user-images.githubusercontent.com/29270715/75652501-508b5080-5c83-11ea-885f-180ea5ba5945.png)

## Button’s Font Family

By default, form elements don’t inherit the font family that is being applied to the <html> or <body> element. Fun fact: I wrote 70% of this article and realized that I didn’t change the button’s font nor wrote a section about it.

To solve that issue, the font-family property should be set to inherit.

```css
.c-button {
    font-family: inherit;
    /* other styles */
}

```
## Disabled state
To indicate that a button is disabled, we can add the disabled attribute to it and then style that with CSS.

```html
<button disabled></button>
```

```css
.c-button[disabled] {
    color: #d2d5db;
    background: #6c7589;
    cursor: not-allowed;
}
```

When a button is disabled, it can’t be focused on the keyboard and it’s removed from the accessibility tree.

## Cursor on hover

The default cursor for the button element is the pointing arrow. I liked this answer on Stackoverflow:

    Buttons are a traditional desktop software UI control - a context where the hand pointer has never been used before the advent of the internet. When web pages started to use the same control, they just kept the button as it was in a desktop environment.

To override that behavior, it’s recommended to change that default cursor into a hand pointing one.

![image](https://user-images.githubusercontent.com/29270715/75652638-a95ae900-5c83-11ea-865f-08649d97b1d7.png)

```css
.c-button {
  min-width: 100px;
  font-family: inherit;
  appearance: none;
  border: 0;
  border-radius: 5px;
  background: #4676d7;
  color: #fff;
  padding: 8px 16px;
  font-size: 1rem;
  cursor: pointer;
}

.c-button:hover {
  background: #1d49aa;
}

.c-button:focus {
  outline: none;
  box-shadow: 0 0 0 4px #cbd6ee;
}

```

# Button with an icon

Sometimes, we need a button with an icon to make it look more prominent or to communicate a specific message. It’s important to implement that inaccessible way.

![image](https://user-images.githubusercontent.com/29270715/75652689-d6a79700-5c83-11ea-8407-bc4c20d28e08.png)

In the example below, we have a button with an icon, and I added an aria-hidden attribute for the icon so it can be hidden from the accessibility tree. I also added focusable=false to avoid the icon being focused in IE.

Notice that I used vertical-align: middle to align the icon vertically with the button content.

```html
<button class="c-button">
    <svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24"><!-- Icon code --></svg>
    Add to fav
  </button>
```
```css
.c-button svg {
    display: inline-block;
    vertical-align: middle;
    fill: #fff;
    width: 20px;
    height: 20px;
    margin-right: 0.25rem;
}

```
The above might work until we need to hide the text and make it an icon button only. How to? First, I need to wrap 

the text in a span element for example, and then I will test and enhance it further.

```html
<button class="c-button c-button--icon">
    <svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24"><!-- Icon code --></svg>
    <span>Add to fav</span>
  </button>
```

It might be tempting to hide the span and call it a day:

```css
.c-button--icon span {
    display: none;
}

```

While the above hides the text and keeps the icon, it’s very bad for accessibility. The button is no longer accessible by screen readers. For example, VoiceOver on macOS announced it as Button only. How to solve that? Well, we have a couple of solutions.

## using svg icons
While I prefer the icons used to be SVG, it’s recommended to combine all the SVGs into one file, and then to call each icon with the <use> element in SVG. See below example:

```html
<svg class="c-icon" width="32" height="32" viewBox="0 0 20 20">
    <use xlink:href="icons.svg#facebook"></use>
</svg>
```
In the example above, the SVG icon with the ID #facebook is called. By doing that, we can reduce the code duplication.

## How To Size The Icon Button

Since the button’s text is no longer visible and we have min-width, the button’s width won’t shrink to the size of the icon. To account for that, it’s better to set a custom width for the icon button.

![image](https://user-images.githubusercontent.com/29270715/75652891-5df50a80-5c84-11ea-9c77-893fbb5c599f.png)

```css
.c-button--icon {
  min-width: initial;
  text-align: center;
  padding: 10px 14px;
}

```

## Hiding The Text Visually
By using the popular .sr-only class, the element can be hidden visually from the screen, but still accessible to screen readers.

```html
<button class="c-button c-button--icon">
    <svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24"><!-- Icon code --></svg>
    <span class="sr-only">Add to fav</span>
  </button>
```

```css
.sr-only {
  border: 0; 
  clip: rect(0 0 0 0); 
  -webkit-clip-path: polygon(0px 0px, 0px 0px, 0px 0px);
  clip-path: polygon(0px 0px, 0px 0px, 0px 0px);
  height: 1px; 
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
  white-space: nowrap;
}
```
## setting font size to zero
By setting the font-size to zero, the span element won’t take any space. So it’s actually hidden!

```css
.c-button--icon span {
    font-size: 0;
}
```

However, I will lean towards the sr-only solution since it appears more logical for me. The font-size kinda looks like a hack, maybe?

## using Aria Label

If there is no a <span> element in the button, then there should be a way to substitute that. One way is to use an aria-label attribute, either on the <button> or the <svg> element.

```html
<button class="c-button c-button--icon" aria-label="Add to fav">
    <svg aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24"><!-- Icon code --></svg>
  </button>

```

# Buttons with multiple lines
![image](https://user-images.githubusercontent.com/29270715/75653069-d22fae00-5c84-11ea-8d7a-bd31e6fe8b3b.png)

We have a button for a subscription form, with a supporting text. How to build that in an accessible way? Let’s see how to handle that.

```html
<button class="c-button">
    <span>Subscribe to our newsletter</span>
    <span>240K+ subscribers</span>
</button>
```

A screen reader will announce that button as “Subscribe to our newsletter 240K+ subscribers”. When a user hears that, it’s confusing because there is no break between any of the two texts. See the screenshot below from Chrome’s accessibility inspector:

![image](https://user-images.githubusercontent.com/29270715/75653102-ebd0f580-5c84-11ea-9b56-de1a25d2f37a.png)

To avoid that confusion, I would prefer to hide the second text from screen readers. We can do that by using an aria-hidden attribute on the span element.

```html
<button class="c-button">
    <span>Subscribe to our newsletter</span>
    <span aria-hidden="true">240K+ subscribers</span>
</button>
```

If you can’t change the HTML markup for some reason, there is a way to add a secondary text for the button. There is a solution that caught my eyes (Seen on Smashing Magazine’s website) for this problem is to place the content with pseudo-elements. That way, screen readers won’t read it. See the CSS below:

```css
.c-button--multiple span:after {
    content: "240K+ subscribers";
    display: block;
    font-weight: 400;
    margin-top: 0.25rem;
}

```

# Anchor Link <a> Vs <button>

## An Anchor Link
It represents a hyperlink that redirects to another page on the website or to link sections on the same page. The four pseudo-classes :hover, :focus, :active, and :visited can be used with it. From an accessibility perspective, the link can be accessed by the enter keyboard key, and screen readers announce it as well.

## A Button Element
The <button type="button"> element does nothing until we specify its job with JavaScript. The pseudo-classes :hover, :focus, and :active can be used with it. From an accessibility perspective, the button can be accessed by the enter or space keyboard keys, and screen readers announces it as well.

From a design perspective, it happens that a web page contains buttons with the same style, and they are different in terms of HTML. To account for that, our .c-button class CSS should be done in a way that makes it works for <button> or <a> elements. Consider the example below:

![image](https://user-images.githubusercontent.com/29270715/75653233-3bafbc80-5c85-11ea-89e7-858f65dbe1c2.png)

Notice that we have “buttons” with the same style. However, the first one is an anchor link <a>, and the second one for the newsletter is a <button> element. That means it’s not necessary that a button should be a <button> in HTML.

There are two additions to the .c-button class, which are text-decoration, and text-align: center. By default, links have an underline with them, and we want to reset that with the class we have. Adding on that, it’s important to center the button’s content in case it wasn’t a <button> element.

```css
.c-button {
    /* other styles */
    /* Works only for anchor links */
    text-decoration: none;
    text-align: center;
}
```

## A <button> Doesn’t Need To Look Like A Button

I liked this example by Scott O’Hara which implements an accessible accordion pattern. At first, the markup looks like the below (Assuming that JavaScript is not available):

![image](https://user-images.githubusercontent.com/29270715/75653282-66017a00-5c85-11ea-8adb-08ed78d74b7d.png)

```html
<div class="accordion" data-aria-accordion>
  <h2 data-aria-accordion-heading>Heading of my panel</h2>
  <div data-aria-accordion-panel>
    <p>Content goes here</p>
  </div>
</div>

```

In case JavaScript is available, the markup above will be converted into an expand/collapse functionality by creating a <button> and appending it inside the <h2> element.

![image](https://user-images.githubusercontent.com/29270715/75653327-7ade0d80-5c85-11ea-9540-19dce10e425f.png)

In that case, using a <button> is the right choice since it does expand/collapse the details content.

# Download Button
When we have a document of any kind and want to have a downloadable link for it, what would you use? Anchor link for the rescue! By adding the download attribute to the link, it can trigger a download when clicked.
![image](https://user-images.githubusercontent.com/29270715/75653363-8f220a80-5c85-11ea-920e-b36f13dff8be.png)

```html
<a href="rtl-101.pdf" download>Download PDF</a>
```

# Dealing With Outline Buttons
![image](https://user-images.githubusercontent.com/29270715/75653404-a3fe9e00-5c85-11ea-9c9a-3d9fac368f36.png)

In the figure above, we have a button that becomes outlined on hover. How to do it in the best possible way? First, the border should be added by default with a transparent color. By doing that, it will prevent the border to be painted on hover.

```css
.c-button {
    border: 2px solid transparent;
    /* other styles */
}

.c-button:hover {
    background: transparent;
    color: #222;
    border-color: #4676d7;
}
```

# Gradient Buttons
While working on my article about CSS positioning, I needed to have a button with a gradient fill.

I wanted to have the result as below:
![image](https://user-images.githubusercontent.com/29270715/75653483-c690b700-5c85-11ea-863f-063caab0e1ec.png)

There are two variations of the buttons, a gradient and an outline one. To achieve that, I need to have a transparent border for the base button (Gradient one). That border will be shown for the outline button only.

```css
.c-button {
      display: inline-block;
      color: #fff;
      background: linear-gradient(to bottom, #00acee, #0072e0);
      font-size: 18px;
      font-weight: 500;
      padding: 12px 26px;
      border-radius: 100px;
      /* A transparent border added for the outline button variation */
      border: 3px solid transparent;
      text-decoration: none;
}

.c-button--outline {
  background: transparent;
  color: var(--color-brand-primary);
  border-color: var(--color-brand-primary);
}
```

However, I got a weird issue and I asked about it in a tweet. See the screenshot below that shows the issue:

![image](https://user-images.githubusercontent.com/29270715/75653880-85e56d80-5c86-11ea-9a8b-bb5817d306ea.png)

Now that you have an idea about how the gradient button looks when it has a transparent border, let me explain the technical reason behind that issue.

Each element has a default background-origin with the value padding-box. What it does is that it resizes the gradient to fit within the boundaries of the border.

I added a large border value to see how the result will become. Notice that the gradient is repeated and its size is equal to the padding of the button element.

![image](https://user-images.githubusercontent.com/29270715/75653944-a9101d00-5c86-11ea-84b7-f8fc60fca687.png)

To solve the issue, the origin of the background should on the border-box, instead of the padding-box:

```css
.c-button {
      /* other styles */
      background-origin: border-box;
}

```

# Using Height Vs. Padding, Which is better?
Each button has a height which could be added by using an explicit height value, or by using padding for the top and bottom sides. Note that the below issues are mostly for anchor link <a> elements.

## Fixed Height

```css
.c-button {
    /* other styles */
    min-width: 120px;
    height: 45px;
}
```
![image](https://user-images.githubusercontent.com/29270715/75654022-d8268e80-5c86-11ea-91be-2e6cb1ffda3b.png)

To fix it and center the text, we can either add padding or use line-height property. By setting line-height with equal or close value to the button’s height, the text will be centered.

```css
.c-button {
    /* other styles */
    min-width: 120px;
    height: 45px;
    line-height: 45px;
}
```

However, the downsides of this method are:

  -  It’s not guaranteed that the button’s text will be always centered. It can be off if the font changes.
  -  When the font-size is increased, the line-height value needs to be tweaked.
  -  The line-height might not work consistently in case the website is multilingual.
  -  It can’t work if we have a button with two lines of text.

## Vertical Padding

By adding an equal value of padding-top and padding-bottom, the button’s content is expected to be centered. Correct? Well, it depends.

There are fonts that do really well in centering, and others are not. Sometimes, one of the padding values needs to be tweaked a bit. Consider the below button:
```css
.c-button {
    /* other styles */
    min-width: 120px;
    padding: 16px 14px;
}
```

![image](https://user-images.githubusercontent.com/29270715/75654105-0e640e00-5c87-11ea-9f4b-30b0f96a76da.png)

In that case, the button’s content looks off-centered. The top padding should be decreased a bit.
```css
.c-button {
    /* other styles */
    min-width: 120px;
    padding: 14px 14px 16px 14px; /* Top, Right, Bottom, Left */
}
```

## Wrapping The Button’s Content In A Span

While researching, I noticed that Adobe’s buttons are a bit off-centered. See the screenshot below:

![image](https://user-images.githubusercontent.com/29270715/75654158-32275400-5c87-11ea-93f3-abe875fae58d.png)

I inspected them and noticed an interesting pattern. The content is wrapped in a <span> element with a fixed height for the button.

```html
<button class="c-button-adobe">
    <span>Save Changes</span>
</button>
```

For a <button> element, the <span> is centered by default. When the height is changed, the content is centered automatically, without padding or anything. See below GIF:

![image](https://user-images.githubusercontent.com/29270715/75654214-5420d680-5c87-11ea-8577-d20a11c92ac4.png)

However, if there is a link that looks like a button, then the <span> needs to be centered. To account for that, we can use flexbox.

```css
.c-button {
    /* other styles */
    display: inline-flex; *To keep the button inline, and flex container at the same time*
    align-items: center;
    justify-content: center;
}
```

# Buttons Inside a Flexbox or Grid Container

You might be wondering, what the heck is the relation between buttons and flexbox/grid? Well, let me tell you.

I was working on a hero section for a project and wanted to vertically center its content. So I used flexbox as below:

```css
.c-hero {
    display: flex;
    flex-direction: column;
    justify-content: center;
}

```
![image](https://user-images.githubusercontent.com/29270715/75654312-8af6ec80-5c87-11ea-9739-7c1e491ffe8d.png)

By default, each flex item is stretched within its parent width and that’s what happened to the button element. To avoid such issues, we need to reset the alignment of it:

```css
.c-button {
    /* other styles */
    align-self: flex-start;
}
```

![image](https://user-images.githubusercontent.com/29270715/75654337-9e09bc80-5c87-11ea-9ec6-68c2fa30c488.png)

Another common issue is when the button is wrapped in a flex container, with flex-direction: row as the default. The button height will stretch to its parent height. To avoid that, we should use align-self property on the button, or align-items on the flex parent.

![image](https://user-images.githubusercontent.com/29270715/75654369-ac57d880-5c87-11ea-9a87-274351ea9195.png)

```css
.c-button {
    align-self: center;
}
```

# using em units

To size buttons properly, em units can be used for that purpose. They’re powerful and very helpful for that job. An em unit is equal to the font-size of the element (px or rem). Consider the below example:

```css
.element {
    font-size: 16px;
    padding: 0.5em;
}
```

The padding value is equal to 16 * 0.5 in that case.

Let’s suppose that we have three sizes of a button: normal, medium, and large. When em is used for padding, width/height, and margins, it can create a fluid button that can be easily resized. Consider the below example:

![image](https://user-images.githubusercontent.com/29270715/75654450-dc9f7700-5c87-11ea-8f5f-801cc3d95518.png)

```css
.c-button {
  /* other styles */
  font-size: 1rem;
  min-width: 6.25em;
  border-radius: 0.3125em;
  padding: 0.625em 1em;
}

.c-button svg {
  width: 1.25em;
  height: 1.25em;
  margin-right: 0.25em;
}
```

```css
.c-button--md {
  font-size: 22px;
}

.c-button--lg {
  font-size: 30px;
}

```

# Animations and transitions
To provide a better experience, it’s important to add a transition when the the button is hovered. The simplest thing is to do a transition on the background color. See the next section of the transition I added.

# final button

```css
.c-button {
  appearance: none;
  font-family: inherit;
  display: inline-block;
  min-width: 100px;
  border: 0;
  border-radius: 5px;
  background: #4676d7;
  color: #fff;
  padding: 10px 16px;
  font-size: 1rem;
  text-decoration: none;
  cursor: pointer;
  transition: 0.3s ease-out;
  
  &:hover {
    background: #1d49aa;
  }
  
  &:focus {
    outline: none;
    box-shadow: 0 0 0 4px #cbd6ee;
  }
}
```
