### ISSUE TITLE
10 Ways to Hide Elements in CSS

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#299]
[link to the post](https://www.sitepoint.com/hide-elements-in-css/)

# 1. opacity and filter: opacity()

he opacity: N and filter: opacity(N) properties can be passed a number between 0 and 1, or a percentage between 0% and 100% denoting fully transparent and fully opaque accordingly.

```css
/* hide element */
.hide:hover .hide-item,
.hide:focus .hide-item {
  opacity: 0;
/*
  alternatively:
  opacity: 0%;
  filter: opacity(0%);
*/
}
```

There’s little practical difference between the two in modern browsers, although filter should be used if multiple effects are applied at the same time (blur, contrast, grayscale etc.)

Opacity can be animated and offers great performance, but be wary that a fully transparent element remains on the page and can trigger events.

metric | effect
-- | --
browser support | good, but IE only supports opacity 0 to 1
accessibility | content not read if 0 or 0% is set
layout affected? | no
rendering required | composition
performance | best, can use hardware acceleration
animation frames possible? | yes
events triggered when hidden? | yes

# 2. color Alpha Transparency
opacity affects the whole element, but it’s also possible to set the color, background-color, and border-color properties separately. Applying a zero alpha channel using rgba(0,0,0,0) or similar renders an item fully transparent:

```css

/* hide element */
.hide:hover .hide-item,
.hide:focus .hide-item {
  color: rgba(0,0,0,0);
  background-color: rgba(0,0,0,0);
}

```

Each property can be animated separately to create interesting effects. Note that transparency can’t be applied to elements with image backgrounds unless they’re generated using linear-gradient or similar.

The alpha channel can be set with:

  -  transparent: fully transparent (in-between animations are not possible)
  -  rgba(r, g, b, a): red, green, blue, and alpha
  -  hsla(h, s, l, a): hue, saturation, lightness, and alpha
  -  #RRGGBBAA and #RGBA

metric | effect
-- | --
browser support | good, but IE only supports transparent and rgba
accessibility | content still read
layout affected? | no
rendering required | painting
performance | good, but not as fast as opacity
animation frames possible? | yes
events triggered when hidden? | yes

# 3. transform
The transform property can be used to translate (move), scale, rotate, or skew an element. A scale(0) or translate(-999px, 0px) off-screen will hide the element:

```js


/* hide element */
.hide:hover .hide-item,
.hide:focus .hide-item {
  transform: scale(0);
/*
  alternatively:
  transform: translate(-999px, 0);
*/
}
```

transform offers excellent performance and hardware acceleration because the element is effectively moved into a separate layer and can be animated in 2D or 3D. The original layout space remains as is, but no events will be triggered by a fully hidden element.

metric | effect
-- | --
browser support | good
accessibility | content still read
layout affected? | no — the original dimensions remain
rendering required | composition
performance | best, can use hardware acceleration
animation frames possible? | yes
events triggered when hidden? | no

# 4. clip-path
The clip-path property creates a clipping region that determines which parts of an element are visible. Using a value such as clip-path: circle(0); will completely hide the element.

```css
/* hide element */
.hide:hover .hide-item,
.hide:focus .hide-item {
  clip-path: circle(0);
}
```

clip-path offers scope for interesting animations, although it should only be relied on in modern browsers.

metric | effect
-- | --
browser support | modern browsers only
accessibility | content still read by some applications
layout affected? | no — the original dimensions remain
rendering required | paint
performance | reasonable
animation frames possible? | yes, in modern browsers
events triggered when hidden? | no

# 5. visibility
The visibility property can be set to visible or hidden to show and hide an element:

```css


/* hide element */
.hide:hover .hide-item,
.hide:focus .hide-item {
  visibility: hidden;
}

```

The space used by the element remains in place unless a collapse value is used.

metric | effect
-- | --
browser support | excellent
accessibility | content not read
layout affected? | no, unless collapse is used
rendering required | composition, unless collapse is used
performance | good
animation frames possible? | no
events triggered when hidden? | no

# 6. display
display is probably the most-used element-hiding method. A value of none effectively removes the element as if it never existed in the DOM.

```css


/* hide element */
.hide:hover .hide-item,
.hide:focus .hide-item {
  display: none;
}
```

However, it’s possibly the worst CSS property to use in the majority of cases. It can’t be animated and will trigger a page layout unless the element is moved out of the document flow using position: absolute or the new contain property is adopted.

display is also overloaded, with options such as block, inline, table, flexbox, grid and more. Resetting back to the correct value after display: none; can be problematic (although unset may help).

metric | effect
-- | --
browser support | excellent
accessibility | content not read
layout affected? | yes
rendering required | layout
performance | poor
animation frames possible? | no
events triggered when hidden? | no

# 7. HTML hidden attribute
The HTML hidden attribute can be added to any element:

```html
<p hidden>
  Hidden content
</p>
```

to apply the browser’s default style:

```css
[hidden] {
  display: none;
}
```
This has the same benefits and flaws as display: none, although it could be useful when using a content management system that doesn’t permit style changes.

# 8. Absolute position
The position property allows an element to be moved from its default static position within the page layout using top, bottom, left, and right. An absolute-positioned element can therefore be moved off-screen with left: -999px or similar:

```css
/* hide element */
.hide:hover .hide-item,
.hide:focus .hide-item {
  position: absolute;
  left: -999px;
}
```

browser support | excellent, unless using position: sticky
-- | --
accessibility | content still read
layout affected? | yes, if positioning is changed
rendering required | depends
performance | reasonable if careful
animation frames possible? | yes, on top, bottom, left, and right
events triggered when hidden? | yes, but it may be impossible to interact with an off-screen element

# 9. Overlay Another Element

An element can be visually hidden by positioning another over the top which has the same color as the background. In this example, an ::after pseudo-element is overlaid, although any child element could be used:

```css
/* hide element */
.hide-item {
  position: relative;
}

.hide-item::after {
  position: absolute;
  content: '';
  top: 0;
  bottom: 100%;
  left: 0;
  right: 0;
  background-color: #fff;
}

.hide:hover .hide-item::after,
.hide:focus .hide-item::after {
  bottom: 0;
}
```

metric | effect
-- | --
browser support | excellent
accessibility | content still read
layout affected? | no, if absolutely positioned
rendering required | paint
performance | reasonable if careful
animation frames possible? | yes
events triggered when hidden? | yes, when a pseudo or child element is overlaid

# 10. Reduce Dimensions

An element can be hidden by minimizing its dimensions using width, height, padding, border-width and/or font-size. It may also be necessary to apply overflow: hidden; to ensure content doesn’t spill out.
```css
/* hide element */
.hide:hover .hide-item,
.hide:focus .hide-item {
  height: 0;
  padding: 0;
  overflow: hidden;
}

```

metric | effect
-- | --
browser support | excellent
accessibility | content still read
layout affected? | yes
rendering required | layout
performance | poor
animation frames possible? | yes
events triggered when hidden? | no

# Hidden Choices
display: none has been the favorite solution to hide elements for many years, but it’s been superseded by more flexible, animatable options. It’s still valid, but perhaps only when you want to permanently hide content from all users. transform or opacity are better choices when considering performance.
