### ISSUE TITLE
Sass !default and themeable design systems

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#310]
[link to the post](https://bradfrost.com/blog/post/sass-default-and-themeable-design-systems/)
I’m working on a couple themeable design systems right now, and we’re architecting components to offer a white list of themeable CSS properties, so each brand can define their design language using design tokens and then pipe those through into the design system’s components.

Making these components sufficiently themeable means making the core components pretty verbose in order to accommodate all the properties we want to allows users to be able to theme. Here’s a basic taste of what we’re talking about here:

![image](https://user-images.githubusercontent.com/29270715/76930381-7749b800-690e-11ea-9345-bf9c63b30156.png)

This is fine, but what if certain themes don’t need to theme all of these properties? We want to avoid shipping all of these unnecessary CSS declarations to the client. Here’s an example of what we want to avoid:

![image](https://user-images.githubusercontent.com/29270715/76930427-8d577880-690e-11ea-8e0e-1f20b6dcd18c.png)

How do we get rid of all of those unneeded properties? Here’s where Sass’s !default feature comes into play. From the docs:

    Normally when you assign a value to a variable, if that variable already had a value, its old value is overwritten. But if you’re writing a Sass library, you might want to allow your users to configure your library’s variables before you use them to generate CSS.

    To make this possible, Sass provides the !default flag. This assigns a value to a variable only if that variable isn’t defined or its value is null. Otherwise, the existing value will be used.

That means that setting up the Sass variables to use null !default will result in only the variables defined by the theme author to get printed.

![image](https://user-images.githubusercontent.com/29270715/76930516-c5f75200-690e-11ea-8ca4-732441ab189c.png)

```scss
$font-color: salmon;
$font-size-huge: 3.5rem !default;
$my-cool-bg: null !default;

.thing {
  color: $font-color;
  font-size: $font-size-huge;
  background-color: $my-cool-bg; /* because $my-cool-bg is set to `null`, `background-color` doesn't get printed to the compiled CSS. Hooray! */
}

$my-cool-bg: purple; /* now setting this to something other than null */

.another-thing {
  color: $font-color;
  font-size: $font-size-huge;
  background-color: $my-cool-bg; /* Hooray! The property gets printed because the value of $my-cool-bg is something pther than null */
}
```

This is a super nice way of keeping the rendered CSS as lean as possible. It’s also really elegant; I thought I’d have to reach for variable-exists(), which would essentially mean authoring a conditional for each optional property, which feels a little verbose and gross.

A few questions in my mind are: I wonder how CSS-in-JS solutions handle this? Is it using a ternary for each optional property? And how would this work for CSS custom properties? While CSS variables are amazing, this seems like a case where having a build step really makes a big difference. I wonder if there’s an elegant Sass/CSS properties mashup to accomplish the same results but spitting out custom properties instead?
