### ISSUE TITLE
CSS viewport units

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#329]
[link to the post](https://ishadeed.com/article/viewport-units/)

# Viewport Width 
The vw unit represents a percentage of the root element width. One vw is equal to 1% of the viewport width.

![image](https://user-images.githubusercontent.com/29270715/78119760-a0973780-7428-11ea-8cee-49bd25d9e59c.png)

When the width of the viewport is 500px, the 50vw will be calculated as below:

```
width = 500*50% = 250px
```

# Viewport Height

The vh unit represents a percentage of the root element height. One vh is equal to 1% of the viewport height.

![image](https://user-images.githubusercontent.com/29270715/78119842-c290ba00-7428-11ea-8036-079576105464.png)

When the height of the viewport is 290px, the 70vh will be calculated as below:

```
height = 290*70% = 202px
```

# vmin unit
The vmin represents the value of the minimum of the width and height of the viewport. If the viewport width is greater than its height, then the value will be calculated based on the height.

We have a mobile in landscape mode, and an element has the vmin unit. In that case, the value will be calculated based on the viewport height, because it’s less than the width.

![image](https://user-images.githubusercontent.com/29270715/78119995-fb309380-7428-11ea-953e-8a62436cffe7.png)

![image](https://user-images.githubusercontent.com/29270715/78120025-0388ce80-7429-11ea-80ee-4c9405515d21.png)

# vmax
It’s the opposite of vmin. The value is calculated based on the maximum width and height.

![image](https://user-images.githubusercontent.com/29270715/78120095-1bf8e900-7429-11ea-9e6e-1cfada35f18c.png)

![image](https://user-images.githubusercontent.com/29270715/78120105-20bd9d00-7429-11ea-836e-9359a289387b.png)

# Use Cases For Viewport Units

## font size
![image](https://user-images.githubusercontent.com/29270715/78120160-3206a980-7429-11ea-94ee-0c9b8951f1dc.png)
CSS viewport units are perfect for responsive typography. For example, we can use the following for an article title:

```css
.title {
    font-size: 5vw;
}

```

Notice that the font size became very small in mobile sizing, this is bad for accessibility and user experience. As far as I know, the minimum font size on a mobile device shouldn’t go beyond 14px. In the GIF, the font size went below 10px.

To solve that issue, we need to give the title a minimum font size that it can’t go below it. CSS calc() to the rescue!

```css
.title {
    font-size: calc(14px + 2vw);
}
```

The calc() CSS function will have a base 14px value, and it will add 2vw to it. With that in hand, the font-size value won’t become too small.

Another important thing to consider is how the font size will behave on large screens, for example, a 27” iMac. What will happen? Well, you guessed it. The font size went to around 95px, which a huge value. To prevent that, we should use media queries at certain breakpoints and change the font-size.

```css
@media (min-width: 1800px) {
    .title {
        font-size: 40px;
    }
}
```

## full screen sections
Sometimes, we need a section to take 100% of the viewport height. This is known as ** full-screen sections**. To do so, we can use the viewport height unit

```css
.section {
    height: 100vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}
```

## Sticky Footer
To solve that, we need to give the main content a height that is equal to viewport height - (header + footer). It’s tricky to do that dynamically, but with CSS viewport units, it’s quite easy.

By adding the 100vh as a height for the body element, we can then use flexbox to make the main element take the remaining space.

```css
body {
    min-height: 100vh;
    display: flex
    flex-direction: column;
{

main {
    /* This will make the main element take the remaining space dynamically */
    flex-grow: 1;
}

```

## Responsive Elements

Suppose that we have a portfolio to showcase our responsive design work, and we have three devices (mobile, tablet, and laptop). Each device contains an image. The goal is to make this 100% responsive in CSS.

![image](https://user-images.githubusercontent.com/29270715/78120646-0637f380-742a-11ea-8237-caf6960847d0.png)

By using CSS grid and viewport units, we can make this fully responsive and dynamic.

```html

<div class="wrapper">
  <div class="device laptop"></div>
  <div class="device mobile"></div>
  <div class="device tablet"></div>
</div>
```

Notice that viewport units are used in the grid-* properties. They’re also used for the border, border-radius, and other properties. All of this will result in a fluid design.

```css
.wrapper {
  display: grid;
  grid-template-columns: repeat(20, 5vw); 
  grid-auto-rows: 6vw;
}

.mobile { 
  position: relative;
  z-index: 1;
  grid-column: 2 / span 3;
  grid-row: 3 / span 5;
}
 
.tablet {
  position: relative;
  z-index: 1;
  grid-column: 13 / span 7; 
  grid-row: 4 / span 4;
  border-bottom: 1vw solid #a9B9dd;
  border-right: solid 3vw #a9B9dd;
}
 
.laptop {
  position: relative;
  grid-column: 3/span 13;
  grid-row: 2 / span 8;
}

/* Viewport units are used for the bottom, left, right, height, and border-radius. Isn't that cool? */
.laptop:after {
    content:"";
    position:absolute;
    bottom: -3vw;
    left: -5.5vw;
    right: -5.5vw;
    height: 3vw;
    background-color: #a9B9dd;
    border-radius: 0 0 1vw 1vw;
}
```

## Breaking out of the container

I have noticed a use case which is most suitable for editorial layouts. A child element that takes 100% width of the viewport, even if its parent width is limited. Consider the below figure:

![image](https://user-images.githubusercontent.com/29270715/78121114-b3127080-742a-11ea-9cca-6c5227067435.png)

To achieve a similar effect, we can use viewport units and some positioning properties. Here is the CSS:

```css
.break-out {
    width: 100vw;
    position: relative;
    left: 50%;
    right: 50%;
    margin-left: -50vw;
    margin-right: -50vw;
}
```

### adding width 100vw
![image](https://user-images.githubusercontent.com/29270715/78121216-d63d2000-742a-11ea-975f-40d0012a5145.png)

### adding margin left -50vw

![image](https://user-images.githubusercontent.com/29270715/78121259-e6ed9600-742a-11ea-8e58-a0087ee24484.png)

### adding left: 50%

![image](https://user-images.githubusercontent.com/29270715/78121303-f53bb200-742a-11ea-9a1f-58a014282437.png)

## Vertical and Horizontal Spacing

Another interesting use-case that I thought about is using viewport units for spacing between elements. This can be used with values like margin, top, bottom, and grid-gap. When used, the spacing will be based on the viewport width or height, which might be useful to make a layout more dynamic.

## Modal
For modals, we need to push them from the top of the viewport. Often, I made this with the top property and I use either percentage or pixel value. However, with viewport units, we can add a spacing that can change based on the viewport’s height.

![image](https://user-images.githubusercontent.com/29270715/78121516-32a03f80-742b-11ea-9d7a-e06747e2a473.png)

## Page Header

The vertical padding is small on mobile, and it gets larger on greater viewports. What about using viewport units? Let’s explore that.

```css
.page-header {
    padding-top: 10vh;
    padding-bottom: 10vh;
}

.page-header h2 {
    margin-bottom: 1.5vh;
}

```

## Grid of items
![image](https://user-images.githubusercontent.com/29270715/78121771-87dc5100-742b-11ea-8634-58b016083978.png)

By using viewport units inside grid-gap, we can get the desired result. Notice that I used CSS calc() function as well. The goal of using calc() is to have a base vertical and horizontal gap.

```css
.wrapper {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    grid-gap: calc(14px + 1vh) calc(14px + 0.5vw);
}
```

# Vmin and Vmax use cases
The use-case is about the top and bottom padding for a page header element. The padding is often reduced when the viewport is small (mobile). By using vmin, we can have a fluid top and bottom padding based on the viewport smaller dimension (width or height).

```css
.page-header {
    padding: 10vmin 1rem;
}
```

# vertical media queries and viewport units
By using vertical media queries, we can check if the user phone or tablet is in landscape mode. If it is, then it won’t make sense to have a section taking the full height of the viewport by using height: 100vh.

![image](https://user-images.githubusercontent.com/29270715/78122065-ef929c00-742b-11ea-9a66-5ad273cb2d2b.png)

```css
@media (orientation: landscape) {
    .section {
        height: 100vh;
    }
}
```

# aspect ratio
We can use vw unit to create responsive elements that maintain its aspect ratio regardless of the viewport size. Let’s explore that.

We will need to decide on the aspect ratio we need. For this example, I will use 9/16.

```css

section {
    /* 9/16 * 100 */
    height: 56.25vw;
}
```

# using viewport units for graphical elements

## Scroll Issue On Mobile

There is a common issue in mobile which cases a scroll, even if 100vh is used. The reason is that the address bar height is in view. Louis Hoebregts wrote an article about that with a simple and easy fix.

```css
.my-element {
  height: 100vh; /* Fallback for browsers that do not support Custom Properties */
  height: calc(var(--vh, 1vh) * 100);
}
```

```js
// First we get the viewport height and we multiple it by 1% to get a value for a vh unit
let vh = window.innerHeight * 0.01;
// Then we set the value in the --vh custom property to the root of the document
document.documentElement.style.setProperty('--vh', `${vh}px`);
```
