### ISSUE TITLE
Everything About Auto in CSS

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#333]
[link to the post](https://ishadeed.com/article/auto-css/)

# Width: auto
When an element has auto as a value for width, it can have margin, padding, and border without becoming bigger than its parent element. The width of its content box will be the content itself with the subtraction of margin, padding, and border.

![image](https://user-images.githubusercontent.com/29270715/78222500-16f96f80-74e5-11ea-9e18-ad1489479451.png)

Let’s see the above mockup as an example in action.

```html
<div class="wrapper">
  <div class="item"></div>
</div>
```

```css
* {
    box-sizing: border-box;
}

.wrapper {
      max-width: 600px;
      margin: 2rem auto 0;
      padding: 1rem;
}

.item {
      padding: 1rem;
      margin: 0 50px;
      border: 15px solid #1f2e17;
}
```
Everything is ok. The item is constrained within its parent.

However, what will happen if we change the item’s width to 100% instead of auto? The item will take 100% of its parent, plus the margins on the left and the right sides.

![image](https://user-images.githubusercontent.com/29270715/78222746-735c8f00-74e5-11ea-9f8a-0f9cc6433126.png)

# Use Cases For width: auto

![image](https://user-images.githubusercontent.com/29270715/78222772-7ce5f700-74e5-11ea-9bcb-6f8ef9f428e7.png)

We have a group of buttons. On mobile, we want them to be next to each other (each button wrapper takes 50% of its parent), while on desktop, each one should take the full width of their parent. How to do it?

```html
<div class="group">
    <div class="group__item">
        <button class="c-button">Sign In</button>
    </div>
    <div class="group__item">
        <button class="c-button c-button--ghost">Register</button>
    </div>
</div>
```

```css
.group {
    display: flex;
}

.group__item {
    width: 50%;
}
```

```css
@media (min-width: 800px) {
    /* Revert the wrapper to a block element instead of flex */
    .group {
        display: block;
    }

    .group__item {
        width: auto;
    }
}
```

Since the .group__item is a block element, using width: auto makes it fill the available space of its parent nicely.

# Margins and auto keyword

For margins, the most common use case to center elements with know widths horizontally.

![image](https://user-images.githubusercontent.com/29270715/78222885-b7e82a80-74e5-11ea-804e-45cee0d06c66.png)

```css
.element {
    margin-left: auto;
    margin-right: auto;
}

```

![image](https://user-images.githubusercontent.com/29270715/78222909-c2a2bf80-74e5-11ea-9709-c85ff00d0a05.png)

# Margin auto With Absolutely Positioned Elements

![image](https://user-images.githubusercontent.com/29270715/78222929-ca626400-74e5-11ea-8d22-49e3c50ee58b.png)

Another less common use-case to center an absolutely positioned element is margin: auto. When we have an element that should be centered horizontally and vertically inside its parent, we might be tempted to use translateX or translateY.

For the above technique to work, we need the following:

   - Width and height to be set.
   - The element should have position: absolute

```html
<div class="wrapper">
  <div class="item">I am centered.</div>
</div>
```

```css
.wrapper {
    position: relative;
}

.item {
    width: 200px;
    height: 100px;
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    margin: auto;
}

```

# flexbox
Using auto margins with flexbox can be very useful in some use cases. When a child item has an auto margin, it will be pushed to the far to the opposite side. For example, if a flex item has margin-left: auto, it will be pushed to the far right.

```css
.wrapper {
    display: flex;
}

.item-2 {
    margin-left: auto;
}
```
![image](https://user-images.githubusercontent.com/29270715/78228429-67c19600-74ee-11ea-80e7-2576a2fe2b43.png)

```css
.item-2 {
    margin-top: auto;
}
```

![image](https://user-images.githubusercontent.com/29270715/78228453-7019d100-74ee-11ea-8e8e-912281d84ca9.png)

```css
.item-1 {
    margin: auto;
}
```

![image](https://user-images.githubusercontent.com/29270715/78228483-79a33900-74ee-11ea-830d-e7eff07c4935.png)

# flex property and auto keyword

In flexbox, we can use flex: auto for a child item. What does that mean? Well, let me explain that. When a child item has flex: auto, that is equivalent to flex: 1 1 auto which means the following:

```css
    .item {
        flex-grow: 1;
        flex-shrink: 1;
        flex-basis: auto;
    }
```

An item with flex: auto will be sized based on its width and height, but it can grow or shrink depending on the extra space available. I didn’t know about that before researching for this article!

```html
<div class="wrapper">
  <div class="item item-1">Item</div>
  <div class="item">Item</div>
  <div class="item">Item</div>
</div>
```

```css
.wrapper {
    display: flex;
    flex-wrap: wrap;
}

.item {
    width: 120px;
    height: 500px;
}

.item-1 {
    flex: auto;
}
```

![image](https://user-images.githubusercontent.com/29270715/78228612-a6efe700-74ee-11ea-8713-2c6d409915ad.png)

# css grid and auto
![image](https://user-images.githubusercontent.com/29270715/78228650-b0794f00-74ee-11ea-934b-d42403a8d2fd.png)

# Grid and auto Margins
When CSS grid is used, auto margins can be used to achieve results that are similar to flexbox. When we have a grid, and of the grid items has margin-left: auto for example, it will be pushed to the right and its width will be based on its content length.

![image](https://user-images.githubusercontent.com/29270715/78228701-c38c1f00-74ee-11ea-9b23-e5711c91c264.png)

```css
.item-1 {
        margin-left: auto;
    }
```

![image](https://user-images.githubusercontent.com/29270715/78228734-cedf4a80-74ee-11ea-9370-ff960af74585.png)

# right to left layouts
It worth mentioning that using margin-left: auto or margin-right: auto might work great for the left to right layouts, like English. However, beware to flip those values when working on a multilingual website. Even better, I would recommend using flexbox or grid properties in case the job can be done with them. If not, then make using auto margins your last resort and instead, use CSS logical properties.

# overflow property
When we have an element, we should think about the minimum and maximum content it should take. If the content exceeded the maximum, then we need to show a scrollbar.

You might be tempted to use the following:
```css
.element {
    overflow-y: scroll;
}
```
However, this might show a scrollbar even if the content height is short. See the example below:

![image](https://user-images.githubusercontent.com/29270715/78228860-f1716380-74ee-11ea-9209-0f297a80e2a1.png)

By using auto keyword instead, we can assure that the scrollbar won’t be shown unless the content height is bigger than its container.

# positioning properties
For the CSS positioning properties top, right, bottom, and left, we can use the auto keyword as a value for them. 

![image](https://user-images.githubusercontent.com/29270715/78228956-0c43d800-74ef-11ea-99ef-16db0661a4e0.png)

```css
.wrapper {
    position: relative;
    padding: 16px;
}

.item {
    position: absolute;
    width: 100px;
    height: 100px;
}


```

The default value for left is 16px! Why did that happen even I didn’t set it? Well, the reason is that an absolutely positioned element is relative to its closest parent with position: relative. That parent has padding: 16px, so the child item is positioned 16px from the top and left sides. Interesting, no?

How to reset the left on larger viewports? We can’t use left: 0 as this will stick the child to the edge, which is not what we want. 

![image](https://user-images.githubusercontent.com/29270715/78229053-33020e80-74ef-11ea-8e05-1bc7702ed3ea.png)
```css
.item {
    position: absolute;
    left: 100px;
    width: 100px;
    height: 100px;
}

@media (min-width: 800px) {
    .item {
        /* This is equivalent to left: 16px */
        left: auto;
    }
}
```

# use cases and examples

## tooltip arrow

For a tooltip, we need a pointing arrow to make it more clear for the user. In case we’re working on a design system, we should account for multiple states. For example, a tooltip with an arrow pointing to the left, and another one to the right.

![image](https://user-images.githubusercontent.com/29270715/78229162-56c55480-74ef-11ea-9f0a-5b7baf969e58.png)

```css
.tooltip:before {
    /* Arrow code */
    position: absolute;
    left: -15px;
}

/* This is a version where the arrow is pointing to the right */
.tooltip.to-right:before {
    /* Arrow code */
    position: absolute;
    left: auto;
    right: -15px;
}
```

Notice that I used left: auto to override the left: -15px in the initial implementation. For your information, this is used a lot and I would recommend going with the following instead:

```css
.tooltip:before {
    position: absolute;
    right: 100%;
}

.tooltip.to-right:before {
    /* Arrow code */
    position: absolute;
    right: auto;
    left: 100%;
}
```

## card component
![image](https://user-images.githubusercontent.com/29270715/78229235-6f356f00-74ef-11ea-952f-69a235805adb.png)

```css
.card .icon {
    position: absolute;
    left: 15px;
    top: 15px;
}

.card.is-right .icon {
    left: auto;
    right: 15px;
}
```

# flexbox and auto margins

![image](https://user-images.githubusercontent.com/29270715/78229291-82e0d580-74ef-11ea-98fe-76715146a86e.png)

## CSS Grid and Auto Margins

![image](https://user-images.githubusercontent.com/29270715/78229343-9724d280-74ef-11ea-9074-e1f8604959d9.png)

```html
<p class="input-group">
    <label for="">Full Name</label>
    <input type="email" name="" id="">
</p>
```

```css
.input-group {
  display: grid;
  grid-template-columns: 1fr;
  grid-gap: 1rem;

  @media (min-width: 700px) {
    grid-template-columns: 0.7fr 2fr;
  }
}
```

I want to align the label to the left edge of the input. To do that, I need to apply the following:

```css
.input-group label {
    margin-left: auto;
}
```
![image](https://user-images.githubusercontent.com/29270715/78229414-aefc5680-74ef-11ea-86c3-b3fb88bfa654.png)

# modal design

![image](https://user-images.githubusercontent.com/29270715/78229435-b6236480-74ef-11ea-9480-7865ab1b52ab.png)

```css
.modal-body {
    overflow-y: auto;
}
```
