### ISSUE TITLE
 How to Create a “Skip to Content” Link

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#351]
[link to the post](https://css-tricks.com/how-to-create-a-skip-to-content-link/)

Skip links are little internal navigation links that help users move around a page. It’s possible you’ve never actually seen one before because they’re often hidden from view and used as an accessibility enhancement that lets keyboard users and screen readers jump from the top of the page to the content without have to go through other elements on the page first.

In my opinion, the best way to implement a skip link is to hide it and then bring it into view when it is focused. So, let’s say we have a link in the HTML:

```html
<a class="skip-to-content-link" href="#main">
  Skip to content
</a>
```

…we can give it an absolute position and translate it off the screen:

```css
.skip-to-content-link {
  left: 50%;
  position: absolute;
  transform: translateY(-100%);
}
```

Then we can bring it back into view when it’s in focus and style it up a bit in the process:
```css
.skip-to-content-link {
  background: #e77e23;
  height: 30px;
  left: 50%;
  padding: 8px;
  position: absolute;
  transform: translateY(-100%);
  transition: transform 0.3s;
}

.skip-to-content-link:focus {
  transform: translateY(0%);
}
```

This will hide our link until it is focused and then put it into view when it becomes focused.

# Our sample website

I built a [sample website](https://css-tricks.com/how-to-create-a-skip-to-content-link/) that we will use to demonstrate a skip link.
The website has a number of navigation links but, in the interest of time, there are only two pages: the home page and the blog page. This is all we need to see how things work.

# identifying the problem
Here’s the navigation we’re working with:

![image](https://user-images.githubusercontent.com/29270715/80197571-883cc600-863e-11ea-8dcd-d9f2e1472720.png)

In total, we have eight navigation items that a keyboard user and screen reader must tab through before reaching the main content below the navigation.

That’s the problem. The navigation may be irrelevant for the user. Perhaps the user was given a direct link to an article and they simply want to get to the content.

This is a perfect use case for a skip link.

# creating the link
There are a couple of approaches to creating a Skip to content link.  What I like to do is similar to the Sky News example, which is hiding the link until it is focused.  That means we can drop the link at or near the top of the page, like inside the <header> element.

```html
<header>
  <a class="skip-link" href='#main'>Skip to content</a>
  <!-- Navigation-->
</header>
```
This link has a .skip-link class so we can style it. Thehref attribute points to #main, which is the ID we will add to the <main> element that comes further down the page. That’s what the link will jump to when clicked.

```html
<header>
  <a class="skip-link" href='#main'>Skip to content</a>
  <!-- Navigation-->
</header>
 
<!-- Maybe some other stuff... -->
 
<main id="main">
  <!-- Content -->
</main>
```

Now it’s time to make it look pretty. We must first fix the positioning and only show our skip link when it is in focus.

```css
.skip-link {
  background: #319795;
  color: #fff;
  font-weight: 700;
  left: 50%;
  padding: 4px;
  position: absolute;
  transform: translateY(-100%);
}

.skip-link:focus {
  transform: translateY(0%);
}
```

The magic here is in the transform property, which is hiding and showing our skip link depending on whether it is focused or not. Let’s make it look a little nicer with a quick transition on the transform property.

```css
.skip-link {
  /* Same as  before */
  transition: transform 0.3s;
}
```

# It’s OK to use more than one link!
Right now, the link only serves one purpose and that is skip to the content of our website. But we don’t have to stop there.

We can go even further and create a skip link that has more options, such as a way to jump to the footer of the site. As you might imagine, this is quite similar to what we’ve already done.

Let’s make the blog page of the example site a little more usable by using multiple skip links. It’s common for blogs to use AJAX that loads in more posts when reaching the bottom of the page. This can make it very difficult to get to the footer of the website. That’s the problem we want to solve in this case.

So let’s add a second link that bypasses all that auto-loading business and jumps the user straight to a #footer element on the page.

```html
<div class="skip-link" >
  Skip to <a href='#main'>content</a> or <a href='#footer'>footer</a>
</div>
```

We also need to amend our CSS a little and use the :focus-within pseudo selector.

```css

.skip-link {
  transform: translateY(-100%);
}

.skip-link:focus-within {
  transform: translateY(0%);
}

```

This is saying if anything within our .skip-link element has focus, then we show it. Sadly, neither Internet Explorer nor Opera Mini support focus-within, but its coverage is pretty darn good and there is a polyfill available.

Last thing we need to do is make sure there’s an ID on our footer element so the link has something to jump to.

```html
<footer id="footer">
```

# Jumping to conclusions

Are you using skip links on your site? Or, if not, does this convince you to use one? I hope it’s clear that skip links are a great value add when it comes to the accessibility of a site. While it’s not a silver bullet that solves every accessibility need, it does solve some use cases that make for a much more polished user experience.

FS, following an anchor link only moves focus if the item can accept focus. In this example, <main> is not a control nor interactive content, so it does not accept focus. Adding tabindex="-1" allows it to accept focus without putting it in the tab order of the page. If you used tabindex="0" then it would be a tab-stop when tabbing through the page, which nobody wants.
