### ISSUE TITLE
Pimp your Blog: Make a Reading Progress Bar

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#361]
[link to the post](https://dev.to/robole/pimp-your-blog-by-adding-a-reading-progress-bar-573i)

# the progress bar
The progress bar is sticky and only appears when the post comes into view. Scroll down and you will see a funky purple bar as you go. 💜

# HTML
I chose to use <progress>, this is a semantic HTML match for the job, swipe right! ✅
o
We use the following attributes:

   - max describes how much work the task requires. We set this to 100 and we have a range of 0 to 100 for possible values.
   - value specifies how much of the task has been completed. We give it an initial value of 0, and this is what we update in JavaScript as the user scrolls.

# css
We want the progress bar to stick to the top of the post, so we use the properties: position: sticky; and top: 0;. We use all the browser prefixes to avoid any compatibility hiccups.

For the styling of the bar itself, I have clarified what is what by using CSS variables, as you can see you need to cater to 3 different Browser groups for consistent styling, using different properties for the same outcome. It looks good in Firefox and Chrome for sure, I haven't checked it in other Browsers.

```css
:root {
  --progress-width: 100%;
  --progress-height: 8px;
  --progress-bar-color: rgb(115, 0, 209);
  --progress-bg: none;
  --progress-border-radius: 5px;
}

progress {
  position: -moz-sticky;
  position: -ms-sticky;
  position: -o-sticky;
  position: -webkit-sticky;
  position: sticky;
  top: 0;
}

/*Target this for applying styles*/
progress[value] {
  /* Reset the default appearance */
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;

  /* Get rid of default border in Firefox. */
  border: none;

  width: var(--progress-width);
  height: var(--progress-height);

  /* Firefox: any style applied here applies to the container. */
  background-color: var(--progress-bg);
  border-radius: var(--progress-border-radius);

  /* For IE10 */
  color: var(--progress-bar-color);
}

/* For Firefox: progress bar */
progress[value]::-moz-progress-bar {
  background-color: var(--progress-bar-color);
  border-radius: var(--progress-border-radius);
}

/* WebKit/Blink browsers:
    -webkit-progress-bar is to style the container */
progress[value]::-webkit-progress-bar {
  background-color: var(--progress-bg);
  border-radius: var(--progress-border-radius);
}

/*-webkit-progress-value is to style the progress bar.*/
progress[value]::-webkit-progress-value {
  background-color: var(--progress-bar-color);
  border-radius: var(--progress-border-radius);
}

```

# javascript
I use an Intersection Observer, which tells us when the post is in view. We use this to ensure that we only update the progress bar when it is in view. 

To find out what is our current position in the post, we check the top coordinate of its bounding box. If it is negative, then we have scrolled into (or past) our post by some amount, we take this value and divide it by the height of the bounding box to get the percentage scrolled.

The last piece is to add a scroll listener for the page (window), which calls our function to update the progress bar.

```js
const post = document.getElementById("post");
const progress = document.getElementById("reading-progress");
let inViewport = false;

let observer = new IntersectionObserver(handler);

observer.observe(post);

//Whenever the post comes in or out of view, this handler is invoked.
function handler(entries, observer) {
    for (entry of entries) {
        if (entry.isIntersecting) {
          inViewport = true;
        } else {
          inViewport = false;
        }
    }
}

// Get the percentage scrolled of an element. It returns zero if its not in view.
function getScrollProgress(el) {
  let coords = el.getBoundingClientRect();
  let height = coords.height;
  let progressPercentage = 0;

  if (inViewport && coords.top < 0) {
    progressPercentage = (Math.abs(coords.top) / height) * 100;
  }

  return progressPercentage;
}

function showReadingProgress() {
    progress.setAttribute("value", getScrollProgress(post));
}

//scroll event listener
window.onscroll = showReadingProgress;

```

# Optimize the Code 

The performance of our code is fine, but can be improved. If you are interested, read on!

There are 2 parts of our code that make it perform sub-optimally.

The first part is that some methods trigger the Browser to recalculate the layout (known as reflow in Mozilla's terminology). This is an expensive operation and should be done only when necessary. When we call getBoundingClientRect(), we trigger this.

The second part is that scroll events can fire at a high rate. If the event handler is executed at this rate, it can be wasteful. 

# only trigger layout when necessary
We can change our logic a bit so that getBoundingClientRect() is only called when the post is in the viewport.

![image](https://user-images.githubusercontent.com/29270715/81051535-8c3fd200-8ee1-11ea-8a77-eafa70464fe0.png)

# Optimize the event handler

We want to limit how often the scroll event handler is called to update the progress bar.

Debouncing regulates the rate at which a function is executed over time, and is a common optimization technique.

We have a few options:

  -  You can use libraries that have a debounce function such as Lodash and Underscore.
  -  You can use the requestAnimationFrame callback.
  -  You can make your own debounce implementation.

The recommendation is to use requestAnimationFrame if you are "painting" or animating properties directly. We are changing the value property, which triggers painting, so we will go with it.

The advantage we gain with requestAnimationFrame is that the Browser executes changes the next time a page paint is requested, whereas with a debounce function it executes at a pre-determined rate that we pick. 

```js
var timeout;

window.onscroll = function () {
    if (timeout) {
        window.cancelAnimationFrame(timeout);
    }

    timeout = window.requestAnimationFrame(function () {
        showReadingProgress();
  }); 
}

```
