### ISSUE TITLE
Selection in CSS

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#369]
[link to the post](https://ishadeed.com/article/selection-in-css/)

> The ::selection CSS pseudo-element applies styles to the part of a document that has been highlighted by the user (such as clicking and dragging the mouse across text).

To use the ::selection pseudo-element, all you need to do is the following:

```css
p::selection {
   color: #fff;
   background-color: #000; 
}

```

It’s worth noting that only color, background, and text-shadow properties are supported with ::selection.

# Custom Selection

What if we want a custom selection effect? For example, controlling the height of selection, and having a custom background? See the below figure:

![image](https://user-images.githubusercontent.com/29270715/81918927-df5b0880-95f6-11ea-8c06-12020ab3e9dd.png)

It’s possible, but a bit tricky. Here is an explanation of how it’s done:

 -   We add a pseudo-element with the same text content. Then, we give it a 50% height with a white background color.
 -   The pseudo-element is positioned above the original text.

```css
p {
  position: relative;
  color: #fff;
}

p:after {
  content: attr(data-content);
  position: absolute;
  color: #000;
  top: 0;
  left: 0;
  width: 100%;
  height: 50%;
  background-color: #fff;
}

p::selection {
  background: rgba(76, 125, 225, 0.18);
}
```

# Animating Selection

While working on the previous demo, I asked myself a question: is it possible to animate the selection? For example, while the text is selected and the mouse is not hovering, the height is 50% and When the mouse is hovering, the height can be increased to 80%.

```css
p {
    transition: background 0.3s ease-out;
}

p:hover:after {
  background-size: 100% 80%;
}

```

# Digging user-select Property

The user-select property gives us the ability to wether the user can select a specific text or not. It can be useful to disable text selection in some use-cases, which will be useful for the user to avoid selecting any unwanted neighboring content.

The possible values for the property are:

    none, auto, text, contain, all

# Use Cases

## Text and Icon

If an element has an icon as a symbol or a font icon, then it will be selected within the text. This is not practical and not useful at all. Consider the following:

![image](https://user-images.githubusercontent.com/29270715/81919225-47a9ea00-95f7-11ea-8d59-5b247c50584c.png)

That’s not necessary at all. Notice that it has the aria-hidden attribute to avoid exposing it to screen readers. We can use this:

```css
button span[aria-hidden="true"] {
    user-select: none;
}

```

# Checkbox Input

A common thing that I consider annoying is accidentally selecting the checkbox’s label while clicking on it. See the below figure:

![image](https://user-images.githubusercontent.com/29270715/81919298-64462200-95f7-11ea-9e92-d22c05f7ba9c.png)

```css
label {
    user-select: none;
}

```

# select all text

An interesting value for user-select is all. If applied to a parent element, all text contained within it will be selected with one click only. This could be useful for content that is related and should be selected all together. For example, selecting a code snippet.

```css
.embed-code {
    user-select: all;
}
```
