### ISSUE TITLE
Progressively enhancing radio buttons with SVG whilst staying accessible

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#375]
[link to the post](https://christianheilmann.com/2020/05/05/progressively-enhancing-radio-buttons-with-svg-whilst-staying-accessible/)

# Hiding the radio buttons and styling the label

Hiding things on the web isn’t easy. You want to make them not show up but you also don’t want to make them inaccessible. Non-sighted users and search engines should find content we want to replace with prettier alternatives. Scott O’Hara collected a lot of excellent information on the subject. Applying this knowledge, we can use the following CSS to hide the radio buttons themselves across all kind of browsers and devices. The label will still change the state of the radio button when we click it, so that’s good.

```css
input[type=radio] {
  border: 0;
  clip: rect(0, 0, 0, 0);
  height: 1px;
  overflow: hidden;
  padding: 0;
  position: absolute !important;
  white-space: nowrap;
  width: 1px;
}
```

# Defining the different states

Having hidden the radio buttons, we now need to simulate the different states of the radio button. We can do that in CSS, no JavaScript needed

![image](https://user-images.githubusercontent.com/29270715/82437101-943d6b80-9ab6-11ea-91bc-e3c21dc8b715.png)

```css

/* 
Style each label that is following a input
of the type radio as light grey on mid grey
*/
input[type=radio] + label {
  background: #444444;
  color: #ccc;
}

/* Radio buttons that are currently checked should be green... */        
input[type=radio]:checked + label {
  background: #9AD284;
  color: #000;
}

```

# Reacting to interaction
Having the two states isn’t enough, we also need to react to user actions like hovering with a mouse or focusing the element with the keyboard. This invites interaction and is an important usability feature. Luckily, CSS has both :hover and :focus pseudo selectors to create those.

```css
/* When the user hovers over the label... */
input[type=radio]:hover + label {
  background: #666;
  color: #000;
}
/* When the user focuses the label via keyboard... */
input[type=radio]:focus + label {
  background: #666;
  color: #000;
}
 
/* Radio buttons that are checked hovered over */
input[type=radio]:checked:hover + label {
  background: #fff;
  color: #000;
}
/* Radio buttons that are checked and have focus */
input[type=radio]:checked:focus + label {
  background: #fff;
  color: #000;
}
```

# Adding the SVG buttons

```html
<input type="radio" id="r1" name="aligned" value="left" checked> 
<label for="r1">
  <svg xmlns="http://www.w3.org/2000/svg" 
       fill="#ffffff" height="3em" width="3em" 
       viewBox="0 0 100 100" x="0px" y="0px">
    <rect x="17.04" y="25.36" width="65.91" height="6"></rect>
    <rect x="17.04" y="39.79" width="43.87" height="6"></rect>
    <rect x="17.04" y="54.21" width="65.91" height="6"></rect>
    <rect x="17.04" y="68.64" width="43.87" height="6"></rect>
  </svg>
</label>
```

# Making the SVG icons accessible

The first thing to do is to style the SVG to allow for colour to be changed. We can do this by setting the fill to currentColor which means the colour of the SVG fill will now be the text colour (thanks to Arnout ‘3rdEden’ for the reminder).

```css
svg {
  fill: currentColor;
  height: 2em;
  width: 2em;
}
```

 we need to add a title to each of the SVG elements. This should act like an alternative text to the image when it can’t be seen and you can actually see it when you hover over the element:

![image](https://user-images.githubusercontent.com/29270715/82437311-e3839c00-9ab6-11ea-9369-e45a2943f0ec.png)

However, for screenreaders this isn’t enough. We also need to give the SVG element a role of “img” and announce the title of the SVG using “aria-labelledby” pointing to an ID on the title element:

```html
<input type="radio" id="r1" name="aligned" value="left" checked> 
<label for="r1">
  <svg xmlns="http://www.w3.org/2000/svg" 
       fill="#ffffff" height="3em" width="3em" 
       viewBox="0 0 100 100" x="0px" y="0px" 
       aria-labelledby="title-r1" role="img">
    <title id="title-r1">Aligned Left</title>
    <rect x="17.04" y="25.36" width="65.91" height="6"></rect>
    <rect x="17.04" y="39.79" width="43.87" height="6"></rect>
    <rect x="17.04" y="54.21" width="65.91" height="6"></rect>
    <rect x="17.04" y="68.64" width="43.87" height="6"></rect>
  </svg>
</label>
```

# Adding some fanciness

A small extra I added to the final example is a transition between the states and an inner shadow to make it really obvious which state is currently chosen.

```css
label {
  text-align: center;
  height: 2em;
  width: 2em;
  color: #fff;
  float: left;
  transition: 200ms;
}
input[type=radio]:checked + label {
  background: #9AD284;
  fill: #000;
  color: #000;
  box-shadow: 2px 2px 3px inset #333;
}
```

# An alternative proposal fixing the above issues

he turned the approach around and instead of hiding the radio button and its label text, he positions the SVG above it.

The first thing I liked about his approach is that there is no need for IDs, as everything is contained in the label itself:

```html
<label>
  Aligned Left
  <input type="radio" name="aligned" value="left" checked>
  <svg xmls="http://www.w3.org/2000/svg" viewBox="0 0 100 100" x="0px" y="0px">
    <rect x="17.04" y="25.36" width="65.91" height="6"></rect>
    <rect x="17.04" y="39.79" width="43.87" height="6"></rect>
    <rect x="17.04" y="54.21" width="65.91" height="6"></rect>
    <rect x="17.04" y="68.64" width="43.87" height="6"></rect>
  </svg>
</label>
```

In his CSS, he positions the label relative, sets the text colour to transparent to hide it, and set to overflow to hidden to not expand the label to the full width of the text.

```css
label {
  position: relative;
  display: inline-block;
  overflow: hidden;
  color: transparent;
  width: 2em;
  height: 2em;
  padding: 0;
}
```

He then positions SVG and input as absolute to make the SVG cover all the rest of the elements in the label.

```css
label > input, label > svg {
  position: absolute;
  top: 0;
  left: 0;
}
```

He then sets the width and height of the SVG to 100%, and applies all the other styles to the SVG itself.

```css
label > svg {
  width: 100%;
  height: 100%;
  transition: 200ms;
  fill: currentColor;
}
input[type=radio] + svg {
  background: #444444;
  color: #ccc;
}
```

[alt demo](https://codepen.io/WebReflection/pen/LYpeOaJ)
[demo](https://codepo8.github.io/progressively-enhancing-radio-groups/bare-bones.html)
