### ISSUE TITLE
Applying the open-closed principle to UI components

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#386]
[link to the post](https://learnitmyway.com/open-closed-ui/)

I had an aha moment this week regarding the open/closed principle, which states “software entities (classes, modules, functions, etc.) should be open for extension, but closed for modification” and is the O in SOLID. I have always found this principle to be quite abstract and I didn’t know if I was applying it until now.

```jsx
// src/Button.js
import React from 'react'
import './Button.css'

const Button = () => (
  <button className="Button" type="button">
    Click Me!
  </button>
)

export default Button
```

```css
/* src/Button.css */
.Button {
  background-color: aliceblue;
}

```

```jsx
// src/App.js
import React from 'react'
import './App.css'
import Button from './Button'

const App = () => (
  <div className="App">
    <Button />
  </div>
)

export default App
```

Now our app’s stakeholders have said they would like us to add a new button in papayawhip directly beside the existing button. They have also said there are more buttons to follow. So I parameterise the className in the Button component:

```jsx

// src/Button.js
import React from 'react'

const Button = ({ className }) => (
  <button className={className} type="button">
    Click Me!
  </button>
)

export default Button
```

```jsx
// src/App.js
import React from 'react'
import './App.css'
import Button from './Button'

const App = () => (
  <div className="App">
    <Button className="button-aliceblue" />
    <Button className="button-papayawhip" />
  </div>
)

export default App
```

From now on, by passing className to Button as a prop I can update (extend) the styles without changing (modifying) the Button component:

```css
/* src/App.css */
.button-aliceblue {
  background-color: aliceblue;
}

.button-papayawhip {
  background-color: papayawhip;
}
```

This just fulfilled the open/closed principle!
