### ISSUE TITLE
The Surprising Things That CSS Can Animate

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/learning-to-code#389]
[link to the post](https://codersblock.com/blog/the-surprising-things-that-css-can-animate/)

When you think of animating CSS properties, which ones come to mind? I recently started wondering about the ones that don’t come to mind — properties that aren’t typically associated with animation, but turn out to be animatable.

This articles explores some of the unexpected things that CSS can animate and some nifty things you can do by animating them.

# Understanding Interpolation

When your browser animates a CSS property, it creates a sequence of intermediate values over the course of the animation. This is referred to as interpolation.

Here’s [a widget](https://codepen.io/lonekorean/pen/xxZwpMy) that will animate height on a <div> and show the interpolated values during the animation. Give it a try.

The results are pretty much what you’d expect. Interpolating height values from 80px to 160px is straightfoward: it’s a series of incremented values.

Now let’s do [z-index](https://codepen.io/lonekorean/pen/oNbjpmV).

Yes, you can animate z-index! It’s not visually apparent in this demo, but seeing the interpolated values go from 1 to 5 confirms it. What’s interesting is that we don’t see any decimal points like we did for height. We only get integers, which makes sense for z-index.

Alright, let’s do something wacky. What happens if we try to animate text-transform from [lowercase to uppercase](https://codepen.io/lonekorean/pen/wvMKpOW)?

Something happened! Unless you’re using Safari (sorry). But for everyone else, you can see the text flip from “div” to “DIV”. This is known as a discrete animation and the W3C Web Animations working draft describes the behavior as follows:

In other words, if there’s not a sensible way to gradually interpolate from the start value to the end value, then just switch between them halfway through.

And there’s our spark. If we look beyond properties with obvious gradual visual transitions, we’ll find that a lot of unexpected properties can be animated, either discretely or with unique interpolations.

# Layered Animations

Let’s go back to z-index. You can animate z-index to achieve layered animations. Here’s an example with Big Boo [floating through walls](https://codepen.io/lonekorean/pen/vYLNpoY).

There are 5 walls, each with a z-index of 1 through 5. The Big Boo has its z-index animated from 1 to 6, moving it in front of each wall, before alternating back to move behind each wall.

```css
.boo-move {
    animation: move 6s ease-in-out infinite alternate;
}

@keyframes move {
    from {
        z-index: 1;
        /* `transform` here to appear further away */
    }
    to {
        z-index: 6;
        /* `transform` here to appear closer */
    }
}
```
Here’s another demo that plays with z-index, this time to [animate overlapping cards](https://codersblock.com/blog/the-surprising-things-that-css-can-animate/).

```css
@keyframes swing-forwards {
    0% {
        z-index: 1;
        /* `transform` here to appear further away */
    }
    50% {
        /* `transform` here to swing outwards */
    }
    100% {
        z-index: 2;
        /* `transform` here to overlap inwards and appear closer */
    }
}
```

The z-index starts at 1 (behind) and ends at 2 (in front).

At the same time, the other card swings backwards with this animation. It’s essentially the same, but reversed.

```css
@keyframes swing-backwards {
    0% {
        z-index: 2;
        /* `transform` here to overlap inwards and appear closer */
    }
    50% {
        /* `transform` here to swing outwards */
    }
    100% {
        z-index: 1;
        /* `transform` here to appear further away */
    }
}
```
In both cases, the z-index value flips right in the middle, at 50%. This is the moment when the cards are not overlapping, so changing the z-index won’t cause a card to clip through the other.

# Fade and Go Away

Consider a modal that you want to fade out when dismissed. Animating opacity takes care of that. But even when an element reaches opacity: 0 it’s still there, invisibly covering page content and blocking clicks.

You could use a bit of JavaScript with setTimeout to get rid of the modal at the right time. Another option is to (discretely) animate visibility.

```css
.modal {
    animation: dismiss 1s forwards;
}

@keyframes dismiss {
    to {
        opacity: 0;
        visibility: hidden;
    }
}
```

And here it is [in action](https://codepen.io/lonekorean/pen/vYLNdBY).

But wait a second… if visibility is animated discretely, shouldn’t it flip to hidden halfway through the animation, before the fade has finished? Normally yes, but visibility has special interpolation rules!

But wait a second… if visibility is animated discretely, shouldn’t it flip to hidden halfway through the animation, before the fade has finished? Normally yes, but visibility has [special interpolation rules](https://codepen.io/lonekorean/pen/rNxOpRv)!

# Animating Shadows
The box-shadow property can take multiple sets of values, as a comma-separated list, to create multiple shadows. Here’s some CSS we’ll be using soon.

```css

div {
    box-shadow:
        /* in order: offset-x, offset-y, blur-radius, color */
        0 0 20px #fff,
        -20px 0 80px #f0f,
        20px 0 80px #0ff,

        /* same, except these shadows go inwards */
        inset 0 0 50px #fff,
        inset 50px 0 80px #f0f,
        inset -50px 0 80px #0ff,
        inset 50px 0 300px #f0f,
        inset -50px 0 300px #0ff;
}
```

By animating box-shadow, you animate a list of shadows into another list of shadows. Each shadow in the starting list is interpolated to the corresponding shadow in the ending list. Each interpolation is smooth, unless one has inset and the other doesn’t, in which case the entire animation falls back to being discrete.

Let’s add the following CSS to animate the box-shadow from earlier. This will animate the offset-x values of some of the shadows.

```css
div {
    animation: pulsate 6s linear infinite;
}

@keyframes pulsate {
    50% {
        box-shadow:
            0 0 20px #fff,
            20px 0 80px #f0f,
            -20px 0 80px #0ff,
            inset 0 0 50px #fff,
            inset -50px 0 80px #f0f,
            inset 50px 0 80px #0ff,
            inset -50px 0 300px #f0f,
            inset 50px 0 300px #0ff;
    }
}
```

The result is a soft pulsating effect, with colored shadows [shifting side to side](https://codepen.io/lonekorean/pen/KKVdQPX).

The same concept applies to text-shadow. Hover/tap that chicken nugget to see another animation using [multiple shadows.](https://codepen.io/lonekorean/pen/JjGYpPx)
